### ISSUE TITLE
Cloudwatch Logs Input

### ISSUE THREAD

**Issue by romanr** [graylog-labs/graylog-plugin-aws#25]
Feature request for CloudWatch Logs input to allow collecting CloudWatch logs into Graylog.

**Comment by flyinbutrs** [comment]
I second this. It seems based on the current state that you could use the flow logs input as a generic log group importer via kinesis.  I've done this for other log analysis platforms, so I suspect this could be done relatively easily by changing the parameters.

**Comment by ducksauz** [comment]
I would also like to see this. This probably needs its own Graylog input plugin rather than being an add on to the cloudtrail plugin, as you can push anything into cloudwatch logs (e.g. nginx, tomcat, mongo, j. random service logs, etc).

**Comment by andydude** [comment]
I would also like to see this.

**Comment by radykal-com** [comment]
I would like this too!

**Comment by cessner-nw** [comment]
up vote!

**Comment by lennartkoopmann** [comment]
The latest release, v2.3.1, supports this! Please open tickets with any issues you encounter.

**Comment by julian-berks** [comment]
@lennartkoopmann - having trawled through the docs including the plugin readme, I can't see any evidence that Graylog does pull from "Cloudwatch". The only mention of CloudWatch in the plugin readme, is in the title. 
From what I can see, the plugin only collects data from  "Cloudtrail" and "FlowLogs" and consequently, these 2 aspects are documented in the readme, but nothing for cloudwatch. 
 Is the setup a documentation omission (in which case how do we set it up?) or a mistake in the title?
thanks.

**Comment by lennartkoopmann** [comment]
The input is called "AWS Logs". It reads CloudWatch logs from a Kinesis stream. You are right that this input is not documented yet. I have created #66 to address this. Until then, you can use most of the FlowLogs documentation to set up the `CloudWatch > Kinesis < Graylog` connection, because FlowLogs are, in the end, just CloudWatch logs.

**Comment by copperschnack** [comment]
The Graylog input for AWS Logs works great, thanks Lennart!

For me, the hardest part was getting CloudWatch to forward the Log Group events to my Kinesis Data Stream. I did not manage to set it up via the AWS console, ie. via CloudWatch Rules. What set me on course was the manual for [CloudWatch Logs Subscription Filters with Kinesis.](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/SubscriptionFilters.html#DestinationKinesisExample)

HTH
