### ISSUE TITLE
Need Security Token support for AWS account access

### ISSUE THREAD

**Issue by nfdevelopers** [graylog-labs/graylog-plugin-aws#35]
There is no way to pass the security-token by the AWS credential class as it uses "BasicAWSCredentials" class which has no such provision.
Need to implement "**DefaultAWSCredentialsProviderChain**" or a provision to use "InstanceProfileCredentialsProvider" as I am deploying the graylog server in ec2 clusters.

Faulty code snippets:
**_...
public AWSCredentials getCredentials() {
                        return new BasicAWSCredentials(awsConfig.accessKey(), awsConfig.secretKey());
                    }
..._**

in graylog-plugin-aws/src/main/java/org/graylog/aws/inputs/flowlogs/FlowLogReader.java

Please fix this to use the plugin.

**Comment by radykal-com** [comment]
Check if #36 is what you are looking for.

**Comment by bernd** [comment]
This got implemented in #36.
