### ISSUE TITLE
Not supporting in Graylog 2.2.3

### ISSUE THREAD

**Issue by surajit1188** [graylog-labs/graylog-plugin-aws#37]
getting error 
org.graylog.aws.processors.instancelookup.AWSInstanceNameLookupProcessor - AWS plugin is not fully configured. No instance lookups will happen.

**Comment by joschi** [comment]
@surajit1188 You have to configure the plugin on the *System* / *Configurations* page as described in the README: https://github.com/graylog-labs/graylog-plugin-aws/tree/1.3.2#general-setup
