### ISSUE TITLE
Using it with AssumeRoles

### ISSUE THREAD

**Issue by citosid** [graylog-labs/graylog-plugin-aws#4]
I have an account where I don't have any user, but only IAM roles for each EC2 instance. How can I use this plugin in that environment?

**Comment by jamescarr** [comment]
It doesn't work since the AWS key fields are required. I'll issue a PR this week to add it.

**Comment by ducksauz** [comment]
+1 for this, I want to run my GrayLog environment in EC2 and need this plugin to pull its creds from the metadata service

**Comment by ducksauz** [comment]
For pulling creds from the metadata service on EC2, you can shortcut the hierarchy of credential sources and skip right to the InstanceRole

e.g:

`AmazonS3 s3Client = new AmazonS3Client(new InstanceProfileCredentialsProvider());
`

see https://docs.aws.amazon.com/java-sdk/latest/developer-guide/java-dg-roles.html for more info

**Comment by avdhoot** [comment]
@lennartkoopmann @joschi any update on this please?

**Comment by radykal-com** [comment]
Hello,

I need to use the AssumeRole also. Any update on this?
Looking #27 seems @Impressionist replaced access key auth with the other one.

Maybe to best fit all options would be nice to have a way to choose one way or the other. I'm not a Java developer but I could help with it if needed.

The way it could work is for example, is adding a new checkbox to use AssumeRole auth, if checked, the access key textboxes are not required fields and then, after processing the form data we could create an auth object with the correspoding data and use it in all the clients that are actually using the access key and token.

Dunno the complexity about it or if im absolutely wrong

**Comment by et304383** [comment]
Is this still outstanding?  IAM role support is a must have.

**Comment by joschi** [comment]
@et304383 Would you be willing to sponsor the development of this feature?

**Comment by radykal-com** [comment]
Already implemented https://github.com/graylog-labs/graylog-plugin-aws/pull/36

**Comment by bernd** [comment]
This got implemented in #36 and is available since version 2.3.0.
