### ISSUE TITLE
Input stuck in starting state if plugin not configured previously

### ISSUE THREAD

**Issue by radykal-com** [graylog-labs/graylog-plugin-aws#42]
When installing the plugin for first time (dropping the jar to the plugin dir, for example) and then entering Graylog web interface and configuring a new cloudtrail input from this plugin. If you try to start the new created input it will remain in starting status forever.
To fix it, you need to go to the plugin configuration page, and just press the save button, without need of filling any of the fields. Then come back to the plugin page and try to start it aagain, it will start immediately and start working.

Seems the config page does some kind of initialization that makes the input to don't start if it has not been done previously.

**Comment by bernd** [comment]
@radykal-com Thank you for the report. Can you please check if this is still an issue with the just released version [2.3.1](https://github.com/graylog-labs/graylog-plugin-aws/releases/tag/2.3.1)? I wasn't able to reproduce the issue using 2.3.1.

Thank you!

**Comment by radykal-com** [comment]
I'll check it in a new installation of Graylog 2.3.0

**Comment by radykal-com** [comment]
Yep, plugin version 2.3.1 seems to have it fixed. Thanks you

**Comment by bernd** [comment]
@radykal-com Great! Thank you for the feedback!
